### Create a new lab test
POST http://localhost:3900/api/v1/customers
Content-Type: application/json

{
        "name": "Gowtam paul",
        "email": "gowtam@gmail.com",
        "phoneNo": "6464654654",
        "address": "dfasdfasdf"
}

### Find all filtered lab tests
GET  http://localhost:3900/api/v1/customers


### Find a lab test by id
GET  http://localhost:3900/api/v1/customers/928f6140-8a31-4e18-9efe-e8a7d7e0db13

### Update a lab test
PUT  http://localhost:3900/api/v1/customers/928f6140-8a31-4e18-9efe-e8a7d7e0db13
Content-Type: application/json

{
        "name": "Gowtam paul",
        "email": "gowtama@gmail.com",
        "phoneNo": "6464654654",
        "address": "dfasdfasdf"
}

### Delete a lab test by id
DELETE  http://localhost:3900/api/v1/customers/928f6140-8a31-4e18-9efe-e8a7d7e0db13

