import { useEffect } from 'react'
import Footer from '../components/footer/Footer'
import Navbar from '../components/Navbar/Navbar'
import '../styles/globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import Head from 'next/head'
// import 'bootstrap/dist/js/bootstrap.js'
// import DashboardNavbar from '../components/Dashboard/Navbar'
// import DashBoardFooter from '../components/Dashboard/Footer'

function MyApp({ Component, pageProps }) {

  useEffect(() => {
    import("bootstrap/dist/js/bootstrap");
  }, []);

  return (<>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </Head>

    {Component.PageLayOut ? (
      <div >
        <Component.PageLayOut>
          <Component {...pageProps} />
        </Component.PageLayOut>
      </div>
    ) : (<>
      <Navbar />
      <Component {...pageProps} />
      <Footer />
    </>)}
  </>)
}

export default MyApp
